
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/00_brds.ipynb


#package all into a function
def get_data(file_id):
    import gdown
    url = f'https://drive.google.com/uc?id={file_id}'
    zip_file = 'data/data.zip'
    gdown.download(url, zip_file, quiet=False)

    import  zipfile
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall('data/unzipped_data')


    users_raw = pd.read_csv('data/unzipped_data/nsds_users.csv')
    purchases_raw = pd.read_csv('data/unzipped_data/nsds_purchases.csv')

    return purchases_raw, users_raw