
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/01_production_example.ipynb

from pycaret.classification import *
from flask import Flask
import dill
from brds import *


# load pipeline
model = load_model('model/model_v1')


# with open("model/preprocess_v1.pkl", "rb") as dill_file:
#     preprocess = dill.load(dill_file)

app = Flask(__name__)

@app.route('/<file_id>')
def my_view_func(file_id):
    print("got one request")
    get_data(file_id)


# @app.route("/")
# def hello_world():
#     return "<p>Hello, World!</p>"